### ISSUE TITLE
Invalid syntax in API?

### ISSUE THREAD

**Issue by kroscek** [pgromano/Markov_Models#1]
There seems to be typo error in API.py here right?
import Markov_Models
  File "C:\Users\Allan\Anaconda2\lib\site-packages\markov_models-0.1-py2.7-win-amd64.egg\Markov_Models\api.py", line 11
def Markov_Chain(*args, estimator='KMeans', **kwargs):
SyntaxError: invalid syntax

I already installed pyemma so it's not pyEMMA problem...

**Comment by pgromano** [comment]
I haven't written the package to be compatible with python 2.7, so that is most likely the issue here. I've pushed an update that should be py2.7 compatible for `Markov_Chain`, but there is no guarantees it will work further throughout the rest of the code. I haven't had any Windows platform testing, so if you'd be willing to create a py3 environment I'd greatly appreciate the feedback.

Additionally, the PyEMMA dependency is only used for PCCA+ in the MSM coarse-graining, and the implied timescales for the error estimation. So it's only necessary for the `MSM` class.

This package is basically scikit-learn front end for building Markov chains I've written for our research lab. If you're looking to build MSM, I would recommend you use PyEMMA or MSMbuilder, as they have more features, cross-platform and version support, and have an active team working on them full time.
